# Generated by Django 5.2.6 on 2025-09-15 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter 10-digit US phone number (e.g., 5551234567)', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (US format without country code or special characters)', regex='^[0-9]{10}$')]),
        ),
    ]
