repos:
  # Add Ruff formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Find the latest tag on GitHub for the 'rev' value
    rev: v0.4.4 # Replace with the latest version of Ruff
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix] # Lint, auto-fix, and exit with error if fixes were made
      - id: ruff-format
    
  # Add Black formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black