# Generated by Django 5.2.6 on 2025-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=list, help_text='List containing audio_path, transcription_text, transcription_segments, chunk_id, video_id')),
                ('transcription_model', models.CharField(default='base', help_text='Transcription model used (e.g., Whisper-Base)', max_length=20)),
                ('processing_duration', models.FloatField(blank=True, help_text='Time taken to process in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Metadata',
                'verbose_name_plural': 'Video Metadata',
                'db_table': 'video_metadata',
            },
        ),
    ]
