# Generated by Django 5.2.6 on 2025-09-17 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0002_videochat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.CharField(help_text='Path to extracted audio file', max_length=500)),
                ('transcription_text', models.TextField(help_text='Full transcription text')),
                ('transcription_segments', models.JSONField(default=list, help_text='Timestamped transcription segments')),
                ('whisper_model', models.CharField(default='base', help_text='Whisper model used for transcription', max_length=20)),
                ('processing_duration', models.FloatField(blank=True, help_text='Time taken to process in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Metadata',
                'verbose_name_plural': 'Video Metadata',
            },
        ),
    ]
