# Generated by Django 5.2.6 on 2025-09-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='videos.video'),
        ),
    ]
